name: Build Re:VIEW to make distribution file
# The workflow is triggered on pushes to the repository.
on: [push, workflow_dispatch]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
    # uses v2 Stable version
    # https://github.com/actions/checkout
    - name: checkout source
      uses: actions/checkout@v3
    # Build Artifacts
    - name: Build distribution file
      run: |
        docker pull vvakame/review:5.7
        #./build-in-docker.sh
        docker run -i -t -v $(pwd):/book vvakame/review:5.7 /bin/bash
        cd /book
        ./setup.sh
        REVIEW_CONFIG_FILE=config.yml npm run pdf
    # Upload Distribution file
    - name: Upload distribution file to github artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Output documents
        path: ./articles/*.pdf
